# This is a basic workflow to help you get started with Actions

name: UploadCurseForge

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
    strategy:
      matrix:
        java: [ 16 ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # Cache gradle files
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ${GITHUB_WORKSPACE}/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      # build jars
      - name: Run build task
        run: gradle build

      # Upload to curseforge
      - name: Run upload curseforge task
        run: gradle curseforge

      # Commit CurseForgeLatest.json
      - name: Commit json
        if: always()
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          add: 'CurseForgeLatest.json'

          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: ' Updated CurseForge Version File'
