# This is a basic workflow to help you get started with Actions

name: UploadCurseForge

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }} 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Upload to curseforge
      - name: Run upload curseforge task
        run: gradle curseforge
